trials: 30
unset:
this-is-null: ""
env:
  dataset: "full-${DATA:-data}.csv"
  url: "https://www.${URL-example}.com"
  user:
    name: "${USER:?Define user name}"
    access: "${ACCESS?Define user access}"
renv:
  lang: "@{Lang:-EN}"
  type: "@{Type?Type must be set}"
conf:
  path: "#{env.url}/api/v1/"
  text: "User: #{env.user.name} (#{env.user.access})"
